version: '3.8'

services:
  app:
    build:
      context: .
      target: runtime
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - .:/app
    command: npm run start:dev

  tests:
    build:
      context: .
      target: builder
    env_file:
      - .env
    command: npx dotenv -e .env -- ts-node ./tests/tests.ts
